- name: Ensuring we have local unprivileged user owning mirror content
  user:
    name: "{{ mirror_local_user }}"
    comment: "Local CentOS mirror user"
    home: "/home/{{ mirror_local_user }}-home/"

- name: Importing ssh pub keys for local user
  authorized_key:
    user: "{{ mirror_local_user }}"
    key: "{{ item }}"
  with_items: "{{ mirror_local_user_ssh_keys }}"

- name: Ensuring we have a place to store scripts (legacy compat)
  file:
    path: "/home/{{ mirror_local_user }}-scripts"
    state: directory
    owner: "{{ mirror_local_user }}"
    group: "{{ mirror_local_user }}"

- name: Ensuring we have a place to store mirror content
  file:
    path: "{{ mirror_local_path }}"
    state: directory
    owner: "{{ mirror_local_user }}"
    group: "{{ mirror_local_user }}"
    setype: user_home_dir_t
    mode: 0755

- name: Adding other needed directories on master
  file:
    path: "/home/{{ item }}"
    state: directory
    owner: "{{ mirror_local_user }}"
    group: "{{ mirror_local_user }}"
    setype: user_home_dir_t
    mode: 0755
  with_items:
    - centos-store
    - centos-debuginfo
    - centos-buildlogs
    - centos-cloud
