- import_role:
    name: rsyncd

- name: Dropping the rsyncd snippets for master
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rsyncd.d/{{ item }}"
    mode: 0644
  notify:
    - rebuild_rsyncd
  with_items:
    - 02_centosfull.conf
    - 03_centos_stream_full.conf
    - 06_qateam.conf
    - 09_full-store.conf
    - 10_centos-buildlogs.conf
    - 15_centos_full_debuginfo.conf
    - 16_centos_cloud.conf
    - 95_mastersync.conf
  tags:
    - rsyncd

- name: Needed selinux booleans for rsyncd
  seboolean:
    name: rsync_export_all_ro
    persistent: yes
    state: yes

- name: Distributing custom selinux policies
  copy: 
    src: "selinux/{{ ansible_distribution_version[0] }}/{{ item }}" 
    dest: "/etc/selinux/centos/{{ item }}"
  register: sepolicy
  with_items:
    - centos-msync-rsyncd.pp

- name: reload custom selinux files
  shell: /usr/sbin/semodule -u "/etc/selinux/centos/centos-msync-rsyncd.pp"
  when: ansible_selinux.status == "enabled" and sepolicy.changed

